APT::FTPArchive::Release::Origin "snd-zg01";
APT::FTPArchive::Release::Label "snd-zg01";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Description "snd-zg01 DKMS driver APT repository";
